/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
    "/ip": {
      get: {
        responses: {
          200: {
            content: {
              "application/json": components["schemas"]["IpResponse"];
            };
          };
        };
      };
    };
  }
  
  export type webhooks = Record<string, never>;
  
  export interface components {
    schemas: {
      IpResponse: {
        /** Format: ipv4 */
        origin: string;
      };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
  }
  
  export type external = Record<string, never>;
  
  export type operations = Record<string, never>;
  